### ISSUE TITLE
build failure on ruby 1.9.3

### ISSUE THREAD

**Issue by shawnzhu** [justincampbell/chef-drone#27]
here's the build failure: https://travis-ci.org/justincampbell/chef-drone/jobs/55595928
> Gem::InstallError: ohai requires Ruby version >= 2.0.0.
> An error occurred while installing ohai (8.1.1), and Bundler cannot continue.
> Make sure that `gem install ohai -v '8.1.1'` succeeds before bundling.
> The command "eval bundle install --without integration" failed. Retrying, 2 of 3.

the proper fix should be using chef 11 which depends on ohai 0.7.4

but the real question is, do we still need to support ruby 1.9.x?

**Comment by kri5** [comment]
I think ruby 1.9.x is still widespread, even if outdated.

**Comment by shawnzhu** [comment]
it drops ruby 1.9.3 in chef 12: https://www.chef.io/blog/2014/11/25/ruby-1-9-3-eol-and-chef-12/
