### ISSUE TITLE
Install Drone via Docker

### ISSUE THREAD

**Issue by jmccann** [justincampbell/chef-drone#32]
Drone has a docker container that is built @ https://hub.docker.com/r/drone/drone/.  The Drone instructions state to "install" drone by downloading and running the drone container (http://readme.drone.io/setup/overview/).

I was just curious if there were any pros/cons to installing via package instead of using the container, as this cookbook does, and/or thoughts of allowing it to be deployed via either method.

Thanks!

**Comment by jmccann** [comment]
Opened #33 to demonstrate ability to handle both use cases.

**Comment by jmccann** [comment]
@justincampbell I was wondering your thoughts on this.

**Comment by justincampbell** [comment]
@jmccann Thanks for contributing! I haven't had time to review #33 yet. If it keeps the existing functionality and adds Docker support, then I'm all for it. Would love someone else to test in their env.

**Comment by jmccann** [comment]
#33 has been merged
